apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.persistentVolume.metadata.name}}
spec:
  capacity:
    storage: {{.Values.persistentVolume.spec.capacity.storage}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: {{.Values.persistentVolume.spec.storageClassName}}
  local:
    path: {{.Values.persistentVolume.spec.local.path}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: {{.Values.persistentVolume.spec.nodeAffinity.required.value}}

