apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service_app.metadata.name}}-service
spec:
  type: {{.Values.service_app.spec.type}}
  selector:
    app: {{.Values.service_app.spec.selector}}
  ports:
    - protocol: TCP
      port: {{.Values.service_app.port}}
      targetPort: {{.Values.service_app.targetPort}}
      nodePort: {{.Values.service_app.nodePort}}


