apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service_db.metadata.name}}-service
spec:
  selector:
    app: {{.Values.service_db.spec.selector}}
  ports:
    - protocol: TCP
      port: {{.Values.service_db.port}}
      targetPort: {{.Values.service_db.targetPort}}
